# Netlify設定ファイル - Cooklet PWA
[build]
  # ビルドコマンド
  command = "pnpm run build:netlify"
  # 公開ディレクトリ
  publish = "dist"
  # Node.jsバージョンの指定
  environment = { NODE_VERSION = "18", NPM_FLAGS = "--prefer-offline --no-audit" }

# Netlify Functions設定
[functions]
  directory = "netlify/functions"

# 開発環境設定
[dev]
  command = "pnpm run dev"
  port = 5173

# SPAルーティング対応（React Router用）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify Functions用のCORS設定（本番環境用）
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://cooklet.netlify.app"
    Access-Control-Allow-Headers = "Content-Type, Accept, Origin, X-Requested-With"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# PWA用のヘッダー設定
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache, no-store, max-age=0, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# セキュリティヘッダー
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# 静的アセットのキャッシュ設定
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, max-age=0, must-revalidate"

# 依存関係のキャッシュ設定（ビルド高速化）
# 上記のenvironmentセクションに統合済み

# プラグイン設定（必要に応じて）
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"